apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  containers:
    - name: my-nginx
      image: recuencojones/my-nginx:latest
      ports:
        - containerPort: 80

